In [11]:
from os import listdir
from os.path import join

from unidecode import unidecode

import numpy as np

In [12]:
def terke(text, n):
    """
    Vrne slovar s preštetimi terkami dolžine n.
    """
    # text to lowercase
    text = text.lower()
    # unidecode
    text = unidecode(text)
    # count the frequencies of substrings length n in a string
    freq = {}
    for i in range(len(text) - n + 1):
        sub = text[i:i+n]
        if sub in freq:
            freq[sub] += 1
        else:
            freq[sub] = 1
    return freq

In [16]:
text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Sed euismod, urna eu tincidunt consectetur, nisi nunc gravida
mauris, euismod aliquam nisl nunc euismod nunc. Donec
ultricies, nisl eget consectetur consectetur, nisi nunc
gravida mauris, euismod aliquam nisl nunc euismod nunc.
Donec ultricies, nisl eget consectetur consectetur, nisi
nunc gravida mauris, euismod aliquam nisl nunc euismod nunc.
Donec ultricies, nisl eget consectetur consectetur, nisi
nunc gravida mauris, euismod aliquam nisl nunc euismod nunc."""
terke(text, 3)

{'lor': 2,
 'ore': 1,
 'rem': 1,
 'em ': 1,
 'm i': 1,
 ' ip': 1,
 'ips': 1,
 'psu': 1,
 'sum': 1,
 'um ': 1,
 'm d': 1,
 ' do': 2,
 'dol': 1,
 'olo': 1,
 'or ': 1,
 'r s': 1,
 ' si': 1,
 'sit': 1,
 'it ': 1,
 't a': 1,
 ' am': 1,
 'ame': 1,
 'met': 1,
 'et,': 1,
 't, ': 1,
 ', c': 1,
 ' co': 8,
 'con': 8,
 'ons': 8,
 'nse': 8,
 'sec': 8,
 'ect': 8,
 'cte': 8,
 'tet': 8,
 'etu': 8,
 'tur': 8,
 'ur ': 4,
 'r a': 1,
 ' ad': 1,
 'adi': 1,
 'dip': 1,
 'ipi': 1,
 'pis': 1,
 'isc': 1,
 'sci': 1,
 'cin': 1,
 'ing': 1,
 'ng ': 1,
 'g e': 1,
 ' el': 1,
 'eli': 1,
 'lit': 1,
 'it.': 1,
 't.\n': 1,
 '.\ns': 1,
 '\nse': 1,
 'sed': 1,
 'ed ': 1,
 'd e': 1,
 ' eu': 10,
 'eui': 9,
 'uis': 9,
 'ism': 9,
 'smo': 9,
 'mod': 9,
 'od,': 1,
 'd, ': 1,
 ', u': 1,
 ' ur': 1,
 'urn': 1,
 'rna': 1,
 'na ': 1,
 'a e': 1,
 'eu ': 1,
 'u t': 1,
 ' ti': 1,
 'tin': 1,
 'inc': 1,
 'nci': 1,
 'cid': 1,
 'idu': 1,
 'dun': 1,
 'unt': 1,
 'nt ': 1,
 't c': 4,
 'ur,': 4,
 'r, ': 4,
 ', n': 7,
 ' ni': 11,
 'nis': 11,
 'is

In [17]:
def read_data(n_terke):
    # Prosim, ne spreminjajte te funkcije. Vso potrebno obdelavo naredite
    # v funkciji terke.
    lds = {}
    for fn in listdir("jeziki"):
        if fn.lower().endswith(".txt"):
            with open(join("jeziki", fn), encoding="utf8") as f:
                text = f.read()
                nter = terke(text, n=n_terke)
                lds[fn] = nter
    return lds

In [18]:
data = read_data(3)

In [22]:
[*data.keys()]

['ar_french revolution.txt',
 'ar_usa.txt',
 'ar_world war i.txt',
 'ar_world war ii.txt',
 'ca_usa.txt',
 'ca_world war i.txt',
 'da_french revolution.txt',
 'da_usa.txt',
 'de_french revolution.txt',
 'en_french revolution.txt',
 'en_world war i.txt',
 'en_world war ii.txt',
 'es_usa.txt',
 'es_world war i.txt',
 'es_world war ii.txt',
 'fr_french revolution.txt',
 'hi_french revolution.txt',
 'hu_usa.txt',
 'it_usa.txt',
 'it_world war i.txt',
 'it_world war ii.txt',
 'nl_world war i.txt',
 'nl_world war ii.txt',
 'pt_french revolution.txt',
 'pt_usa.txt',
 'pt_world war i.txt',
 'pt_world war ii.txt',
 'ru_french revolution.txt',
 'ru_usa.txt',
 'ru_world war i.txt',
 'ru_world war ii.txt',
 'si_usa.txt',
 'sl_usa.txt',
 'sr_french revolution.txt',
 'sr_usa.txt',
 'sr_world war i.txt',
 'sr_world war ii.txt',
 'sv_french revolution.txt',
 'sv_usa.txt',
 'sv_world war i.txt',
 'sv_world war ii.txt',
 'uk_usa.txt',
 'uk_world war i.txt',
 'uk_world war ii.txt',
 'zh_usa.txt',
 'zh_wo

In [23]:
data['en_world war i.txt']

{'wor': 20,
 'orl': 20,
 'rld': 20,
 'ld ': 21,
 'd w': 29,
 ' wa': 69,
 'war': 56,
 'ar ': 46,
 'r i': 26,
 ' ii': 11,
 'ii ': 11,
 'i o': 2,
 ' or': 8,
 'or ': 16,
 'r t': 12,
 ' th': 210,
 'the': 208,
 'he ': 193,
 'e s': 40,
 ' se': 28,
 'sec': 8,
 'eco': 10,
 'con': 28,
 'ond': 7,
 'nd ': 108,
 ' wo': 16,
 'ar,': 5,
 'r, ': 15,
 ', o': 6,
 ' of': 89,
 'oft': 1,
 'fte': 6,
 'ten': 5,
 'en ': 16,
 'n a': 36,
 ' ab': 4,
 'abb': 1,
 'bbr': 1,
 'bre': 1,
 'rev': 8,
 'evi': 3,
 'via': 2,
 'iat': 4,
 'ate': 35,
 'ted': 35,
 'ed ': 120,
 'd a': 21,
 ' as': 22,
 'as ': 30,
 's w': 16,
 ' ww': 2,
 'wwi': 1,
 'wii': 1,
 'r w': 7,
 'ww2': 1,
 'w2,': 1,
 '2, ': 1,
 ', w': 19,
 'was': 16,
 's a': 28,
 ' a ': 24,
 'a g': 1,
 ' gl': 3,
 'glo': 3,
 'lob': 3,
 'oba': 2,
 'bal': 3,
 'al ': 32,
 'l w': 7,
 'tha': 10,
 'hat': 8,
 'at ': 18,
 't l': 3,
 ' la': 11,
 'las': 2,
 'ast': 10,
 'ste': 11,
 'd f': 13,
 ' fr': 22,
 'fro': 10,
 'rom': 12,
 'om ': 10,
 'm 1': 2,
 ' 19': 41,
 '193': 16,
 '939': 6,

In [25]:
def idf(term, data_dict):
    """
    Compute inverse document frequency of a term.
    """
    N = len(data_dict)
    n = 0
    for lang, freq in data_dict.items():
        if term in freq:
            n += 1
    return np.log(N / n)

In [30]:
idf("nd ", data)

0.5920510636885765

In [32]:
np.stack([np.array([1,2,3]), np.array([4,5,6])], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
my = np.array([[  31.48125417,  -58.9132087 ],
       [  85.07762503, -136.06374636],
       [ -41.1310431 , -157.07802795],
       [ -54.68760785, -156.49660283],
       [ 110.08200973, -107.67868786],
       [ -34.67985596, -117.55989679],
       [  55.61952631, -193.53433428],
       [  10.6147124 ,  -36.10861649],
       [ -31.57450716, -169.32782204],
       [ -35.72958526, -131.15476172],
       [ -57.49898945, -151.82867814],
       [  77.75507089,  -50.88158946],
       [ 115.94259798, -149.47787907],
       [ -30.01263951,  -64.36050238],
       [ -87.12582671,  -85.7909027 ],
       [  58.43958591, -180.39505787]])

PROJECTION = np.array([[ 20.69548364,  62.75243571],
                       [ 74.29185404, -14.39810189],
                       [-51.91681331, -35.41238311],
                       [-65.47337793, -34.83095806]])

In [39]:
PROJECTION - my[:4,:]

array([[-10.78577053, 121.66564441],
       [-10.78577099, 121.66564447],
       [-10.78577021, 121.66564484],
       [-10.78577008, 121.66564477]])

In [44]:
DATA = np.array([[22.0, 81.0, 32.0, 39.0, 21.0, 37.0, 46.0, 36.0, 99.0],
                 [91.0, 95.0, 65.0, 96.0, 89.0, 39.0, 11.0, 22.0, 29.0],
                 [51.0, 89.0, 21.0, 39.0, 100.0, 59.0, 100.0, 89.0, 27.0],
                 [9.0, 80.0, 18.0, 34.0, 61.0, 100.0, 90.0, 92.0, 8.0],
                 [93.0, 99.0, 39.0, 100.0, 12.0, 47.0, 17.0, 12.0, 63.0],
                 [49.0, 83.0, 17.0, 33.0, 92.0, 30.0, 98.0, 91.0, 73.0],
                 [91.0, 99.0, 97.0, 89.0, 49.0, 96.0, 81.0, 94.0, 69.0],
                 [12.0, 69.0, 32.0, 14.0, 34.0, 12.0, 33.0, 48.0, 96.0],
                 [91.0, 80.0, 20.0, 10.0, 82.0, 93.0, 87.0, 91.0, 22.0],
                 [39.0, 100.0, 19.0, 29.0, 99.0, 31.0, 77.0, 79.0, 23.0],
                 [20.0, 91.0, 10.0, 15.0, 71.0, 99.0, 78.0, 93.0, 12.0],
                 [90.0, 60.0, 45.0, 34.0, 45.0, 20.0, 15.0, 5.0, 100.0],
                 [100.0, 98.0, 97.0, 89.0, 32.0, 72.0, 22.0, 13.0, 37.0],
                 [14.0, 4.0, 15.0, 27.0, 61.0, 42.0, 51.0, 52.0, 39.0],
                 [9.0, 22.0, 8.0, 7.0, 100.0, 11.0, 92.0, 96.0, 29.0],
                 [85.0, 90.0, 100.0, 99.0, 45.0, 38.0, 92.0, 67.0, 21.0]])

np.mean(DATA, axis=1, keepdims=True)

array([[45.88888889],
       [59.66666667],
       [63.88888889],
       [54.66666667],
       [53.55555556],
       [62.88888889],
       [85.        ],
       [38.88888889],
       [64.        ],
       [55.11111111],
       [54.33333333],
       [46.        ],
       [62.22222222],
       [33.88888889],
       [41.55555556],
       [70.77777778]])

In [53]:
all_triplets = set()
for _, freq in data.items():
	for triplet in freq:
		all_triplets.add(triplet)

all_triplets_with_idf = [(triplet, idf(triplet, data)) for triplet in all_triplets]

In [54]:
most_common_tripets = sorted(all_triplets_with_idf, key=lambda x: x[1])[:100]
most_common_tripets

[(' =\n', 0.0),
 ('\n= ', 0.0),
 ('an ', 0.04348511193973889),
 ('.\n=', 0.06595796779179737),
 ('n, ', 0.08894748601649612),
 ('er ', 0.08894748601649612),
 (' st', 0.08894748601649612),
 (', m', 0.08894748601649612),
 ('ran', 0.08894748601649612),
 (' br', 0.08894748601649612),
 ('str', 0.08894748601649612),
 ('sta', 0.1124779834266903),
 ('mer', 0.1124779834266903),
 (', s', 0.1124779834266903),
 (' fr', 0.1124779834266903),
 ('per', 0.1124779834266903),
 (' ma', 0.1124779834266903),
 ('iti', 0.1124779834266903),
 (', f', 0.1124779834266903),
 ('lan', 0.1124779834266903),
 (' po', 0.1124779834266903),
 (' mi', 0.1124779834266903),
 ('ter', 0.1124779834266903),
 (' na', 0.1124779834266903),
 ('ate', 0.1124779834266903),
 (' tr', 0.1124779834266903),
 ('ion', 0.1124779834266903),
 ('e m', 0.1124779834266903),
 ('eri', 0.1124779834266903),
 ('ina', 0.1124779834266903),
 (' pa', 0.1124779834266903),
 (', d', 0.1365755350057507),
 ('e s', 0.1365755350057507),
 (' mo', 0.1365755350057507)